#User module.
post_URI = https://petstore.swagger.io/v2/user
get_URI = https://petstore.swagger.io/v2/user/{username}
put_URI = https://petstore.swagger.io/v2/user/{username}
delete_URI = https://petstore.swagger.io/v2/user/{username}